// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DeskDisplay_SquareLine_Project

#include "../ui.h"

void ui_ScrSleep_screen_init(void)
{
    ui_ScrSleep = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrSleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrSleep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labTimeSleep = lv_label_create(ui_ScrSleep);
    lv_obj_set_width(ui_labTimeSleep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labTimeSleep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labTimeSleep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labTimeSleep, "00:00");
    lv_obj_set_style_text_color(ui_labTimeSleep, lv_color_hex(0xFF8D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labTimeSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labTimeSleep, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);


}
