// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DeskDisplay_SquareLine_Project

#ifndef _DESKDISPLAY_SQUARELINE_PROJECT_UI_H
#define _DESKDISPLAY_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_conHeader;
extern lv_obj_t * ui_conSym;
extern lv_obj_t * ui_labSYMBOL;
extern lv_obj_t * ui_labDESC;
extern lv_obj_t * ui_conPrice;
extern lv_obj_t * ui_labPRICE;
void ui_event_butNext(lv_event_t * e);
extern lv_obj_t * ui_butNext;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_butBack(lv_event_t * e);
extern lv_obj_t * ui_butBack;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
